### ISSUE TITLE
QRSpeed反馈

### ISSUE THREAD

**Issue by fvgfgtxdeujv** [ZGQ-inc/ZGQs_QRbot#2]
QRSpeed登录不了，显示服务器异常

**Comment by ZGQ-inc** [comment]
这个项目我已经不维护了，相关问题请加入[官方交流群](https://jq.qq.com/?_wv=1027&k=oFrO2gLs)提问，其它很多写的比我好的，或者先尝试更新到最新版，[下载地址](https://www.123pan.com/s/k3ryVv-OjBs3.html)

**Comment by fvgfgtxdeujv** [comment]
感谢
